### ISSUE TITLE
error: There was a problem with the editor 'vi'.

### ISSUE THREAD

**Issue by balajinandhu** [google/vim-colorscheme-primary#6]
Not able to close vim using ":wq!"
When I run git pull command, and close the vi editor with :wq! , I am getting "error: There was a problem with the editor 'vi'."

I am unable to rebase hence.

**Comment by balajinandhu** [comment]
It was a problem with git configuration. This fixed it for me:
git config --global core.editor /usr/bin/vim

**Comment by RrNn** [comment]
@balajinandhu that helped me. Thanks 💯

**Comment by aibotian** [comment]
@balajinandhu thank you

**Comment by minhdang241** [comment]
@balajinandhu thank you :3

**Comment by Lucius-lsr** [comment]
thanks!

**Comment by MMahdiSheykh** [comment]
thanks :‌)
